#!/bin/sh

set -eu

export GRADER_SCORES_FILE=output.json

echo "{\"tests\":[]}" > $GRADER_SCORES_FILE

OUTPUT=output.txt

eval $(opam env --switch=5.3.0 --safe)

export GRADER_PROBLEM_TASKS='sum' \
export GRADER_TASK_SCORES='10' \
export GRADER_PROBLEM_NAME='sum' \

if dune build --profile release 2> "$OUTPUT"; then
    dune exec bin/main.exe --profile release
else
    python3 report.py "$OUTPUT" output.json 'sum' 'mult isPrime' '4 10'
fi
